name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        NEXTAUTH_URL: http://localhost:3000

    - name: Run ESLint
      run: npm run lint

  security-headers-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check next.config.js for security headers
      run: |
        if grep -q "Content-Security-Policy" next.config.js; then
          echo "✅ Content-Security-Policy header found"
        else
          echo "❌ Content-Security-Policy header not found"
          exit 1
        fi
        
        if grep -q "X-XSS-Protection" next.config.js; then
          echo "✅ X-XSS-Protection header found"
        else
          echo "❌ X-XSS-Protection header not found"
          exit 1
        fi
        
        if grep -q "Strict-Transport-Security" next.config.js; then
          echo "✅ HSTS header found"
        else
          echo "❌ HSTS header not found"
          exit 1
        fi
